[tool.poetry]
name = "futtydata_automation"
version = "0.1.0"
description = ""
authors = ["ig"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
